package ptolemy;

import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author Federico Ferri <federico.ferri.it@gmail.com>
 */
public class AboutBox extends javax.swing.JDialog {

	public AboutBox(java.awt.Frame parent) {
		super(parent);
		initComponents();
		getRootPane().setDefaultButton(closeButton);
	}

	@Action
	public void closeAboutBox() {
		setVisible(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                closeButton = new javax.swing.JButton();
                javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
                javax.swing.JLabel versionLabel = new javax.swing.JLabel();
                javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
                javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
                javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
                javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
                javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
                javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
                javax.swing.JLabel imageLabel = new javax.swing.JLabel();
                panel1 = new ptolemy.JBubbles();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ptolemy.Application.class).getContext().getResourceMap(AboutBox.class);
                setTitle(resourceMap.getString("title")); // NOI18N
                setMinimumSize(new java.awt.Dimension(562, 245));
                setModal(true);
                setName("aboutBox"); // NOI18N
                setResizable(false);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {
                                formWindowClosed(evt);
                        }
                });
                addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentHidden(java.awt.event.ComponentEvent evt) {
                                formComponentHidden(evt);
                        }
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                formComponentShown(evt);
                        }
                });

                javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ptolemy.Application.class).getContext().getActionMap(AboutBox.class, this);
                closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
                closeButton.setName("closeButton"); // NOI18N

                appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
                appTitleLabel.setText(resourceMap.getString("Application.title")); // NOI18N
                appTitleLabel.setName("appTitleLabel"); // NOI18N

                versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
                versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
                versionLabel.setName("versionLabel"); // NOI18N

                appVersionLabel.setText(resourceMap.getString("Application.version")); // NOI18N
                appVersionLabel.setName("appVersionLabel"); // NOI18N

                vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
                vendorLabel.setText(resourceMap.getString("vendorLabel.text")); // NOI18N
                vendorLabel.setName("vendorLabel"); // NOI18N

                appVendorLabel.setText(resourceMap.getString("Application.vendor")); // NOI18N
                appVendorLabel.setName("appVendorLabel"); // NOI18N

                homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
                homepageLabel.setText(resourceMap.getString("homepageLabel.text")); // NOI18N
                homepageLabel.setName("homepageLabel"); // NOI18N

                appHomepageLabel.setText(resourceMap.getString("Application.homepage")); // NOI18N
                appHomepageLabel.setName("appHomepageLabel"); // NOI18N

                appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
                appDescLabel.setName("appDescLabel"); // NOI18N

                imageLabel.setIcon(resourceMap.getIcon("imageLabel.icon")); // NOI18N
                imageLabel.setName("imageLabel"); // NOI18N

                panel1.setName("panel1"); // NOI18N

                javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
                panel1.setLayout(panel1Layout);
                panel1Layout.setHorizontalGroup(
                        panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 164, Short.MAX_VALUE)
                );
                panel1Layout.setVerticalGroup(
                        panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 194, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(imageLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(closeButton)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(versionLabel)
                                                                        .addComponent(vendorLabel)
                                                                        .addComponent(homepageLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(appVersionLabel)
                                                                        .addComponent(appVendorLabel)
                                                                        .addComponent(appHomepageLabel)))
                                                        .addComponent(appTitleLabel)
                                                        .addComponent(appDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(appTitleLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(appDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(versionLabel)
                                                        .addComponent(appVersionLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(vendorLabel)
                                                        .addComponent(appVendorLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(homepageLabel)
                                                        .addComponent(appHomepageLabel)))
                                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeButton)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
		((ptolemy.JBubbles) panel1).stopAnimation();
	}//GEN-LAST:event_formComponentHidden

	private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		((ptolemy.JBubbles) panel1).startAnimation();
	}//GEN-LAST:event_formComponentShown

	private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
		((ptolemy.JBubbles) panel1).stopAnimation();
	}//GEN-LAST:event_formWindowClosed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton closeButton;
        private javax.swing.JPanel panel1;
        // End of variables declaration//GEN-END:variables
}
